modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="copperequipment"
version="1.0"
displayName="Copper Equipment"
logoFile="copperequipment-forge-logo.png"
authors="Redy1aye"
description="Enjoy your copper armor and tools!"

[[dependencies.copperequipment]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.copperequipment]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"